import SiteFooter from '@/components/layout/home/site-footer';
import SiteNavigation from '@/components/layout/home/site-navigation';
import AuthProvider from '@/context/AuthProvider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <AuthProvider>
        <body className={`${inter.className} min-h-screen flex flex-col`}>
          <SiteNavigation />
          {children}
          <SiteFooter />
        </body>
      </AuthProvider>
    </html>
  );
}
